name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_KEY }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: "full-year"
         
          plugin_languages: yes
          plugin_languages_indepth: yes
